### ISSUE TITLE
IPFS helper

### ISSUE THREAD

**Issue by Sam-Archie** [simpleweb/open-format#16]
## Description

A helper function that takes care of uploading data to NFT storage.

This could be an optional parameter that is passed as part of the deploy function as you would probably want to load your data into IPFS storage when deploying the contract.

### Point of note

The image and or audio files need to be file types i.e look like this:

![Screenshot 2022-06-21 at 10 38 44](https://user-images.githubusercontent.com/68110533/174769424-69b49ccf-d18c-4900-8e48-5c00a0860dd2.png)

**Comment by benjaminreid** [comment]
Going to close this in favour of #68
