### ISSUE TITLE
Subgraph pre-defined methods

### ISSUE THREAD

**Issue by tinypell3ts** [simpleweb/open-format#27]
## Get tokens by factory ID
`await sdk.getTokensByFactoryID([FACTORY_ID_STRING]);`
```
query getTokenByFactoryID($factory_id: String!) {
  tokens(where: {factory_id: $factory_id}) {
    id
    factory_id
    release_type
    ...
  }
}
```

## Get tokens by creator
`await sdk.getTokensByCreator([CREATOR_ADDRESS_STRING]);`
```
query getTokensByCreator($creator: String!) {
  tokens(where: {creator: $creator}) {
    id
    factory_id
    release_type
    ...
  }
}
```

## Search properties
`await sdk.searchProperties([SEARCH_TERM_STRING]);`
```
query searchProperties($value: String!) {
  properties(where: {value_contains_nocase: $value}) {
    key
    value
    tokens {
      id
      factory_id
      release_type
      ...
    }
  }
}
```

## List all minted tokens by owner
`await sdk.getMintedByOwner([OWNER_WALLET_ADDRESS]);`
```
query getMintedByOwner($owner: String!) {
  owner(id: $owner) {
    id
    tokens {
      token {
        id
        factory_id
        release_type
        ...
      }
    }
  }
}
```

**Comment by craigcoles** [comment]
Split out and moved over to discussions:

https://github.com/simpleweb/open-format/discussions/90
https://github.com/simpleweb/open-format/discussions/91
https://github.com/simpleweb/open-format/discussions/92
https://github.com/simpleweb/open-format/discussions/94
